version: '3.7'
services:

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    restart: unless-stopped

    volumes:
      - ./storage:/qdrant/storage
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.rule=Host(`${QDRANT_URL}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=default"
    networks:
      - traefik
networks:
  traefik:
    external: true
