version: '3.7'
services:
  vmagent:
    container_name: vm_agent
    image: victoriametrics/vmagent
    restart: unless-stopped
    depends_on:
      - "victoriametrics"
    volumes:
      - ./agent/vmagentdata:/vmagentdata
      - ./agent/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
      - '--promscrape.configCheckInterval=30'
      - '--remoteWrite.url=http://victoriametrics:8428/api/v1/write'
  victoriametrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics
    restart: unless-stopped
    volumes:
      - ./data:/storage
    command:
      - '--storageDataPath=/storage'
      - '--httpListenAddr=:8428'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.victoria.entrypoints=https"
      - "traefik.http.routers.victoria.rule=Host(`${VMUI_URL}`)"
      - "traefik.http.routers.victoria.tls=true"
      - "traefik.http.routers.victoria.tls.certresolver=default"
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    depends_on:
      - "victoriametrics"
    volumes:
      - ./grafana/grafanadata:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_URL}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=default"
    networks:
      - traefik
networks:
  traefik:
    external: true
